/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LayoutsDefault: typeof import('./components/layouts/Default.vue')['default']
    ReportBug: typeof import('./components/ReportBug.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./components/ui/Button.vue')['default']
    UiInput: typeof import('./components/ui/Input.vue')['default']
    UiNav: typeof import('./components/ui/Nav.vue')['default']
    UiSpinner: typeof import('./components/ui/Spinner.vue')['default']
  }
}
